using ImGuiNET;
using Raylib_cs;

namespace RayWork.RLImgui;

internal static class ImguiKeyMapping
{
    public static readonly IReadOnlyDictionary<ImGuiMouseCursor, MouseCursor> MouseCursorMap =
        new Dictionary<ImGuiMouseCursor, MouseCursor>
        {
            [ImGuiMouseCursor.Arrow] = MouseCursor.MOUSE_CURSOR_ARROW,
            [ImGuiMouseCursor.TextInput] = MouseCursor.MOUSE_CURSOR_IBEAM,
            [ImGuiMouseCursor.Hand] = MouseCursor.MOUSE_CURSOR_POINTING_HAND,
            [ImGuiMouseCursor.ResizeAll] = MouseCursor.MOUSE_CURSOR_RESIZE_ALL,
            [ImGuiMouseCursor.ResizeEW] = MouseCursor.MOUSE_CURSOR_RESIZE_EW,
            [ImGuiMouseCursor.ResizeNESW] = MouseCursor.MOUSE_CURSOR_RESIZE_NESW,
            [ImGuiMouseCursor.ResizeNS] = MouseCursor.MOUSE_CURSOR_RESIZE_NS,
            [ImGuiMouseCursor.ResizeNWSE] = MouseCursor.MOUSE_CURSOR_RESIZE_NWSE,
            [ImGuiMouseCursor.NotAllowed] = MouseCursor.MOUSE_CURSOR_NOT_ALLOWED
        };

    public static readonly IReadOnlyDictionary<KeyboardKey, ImGuiKey> RaylibKeyMap =
        new Dictionary<KeyboardKey, ImGuiKey>
        {
            [KeyboardKey.KEY_APOSTROPHE] = ImGuiKey.Apostrophe,
            [KeyboardKey.KEY_COMMA] = ImGuiKey.Comma,
            [KeyboardKey.KEY_MINUS] = ImGuiKey.Minus,
            [KeyboardKey.KEY_PERIOD] = ImGuiKey.Period,
            [KeyboardKey.KEY_SLASH] = ImGuiKey.Slash,
            [KeyboardKey.KEY_ZERO] = ImGuiKey._0,
            [KeyboardKey.KEY_ONE] = ImGuiKey._1,
            [KeyboardKey.KEY_TWO] = ImGuiKey._2,
            [KeyboardKey.KEY_THREE] = ImGuiKey._3,
            [KeyboardKey.KEY_FOUR] = ImGuiKey._4,
            [KeyboardKey.KEY_FIVE] = ImGuiKey._5,
            [KeyboardKey.KEY_SIX] = ImGuiKey._6,
            [KeyboardKey.KEY_SEVEN] = ImGuiKey._7,
            [KeyboardKey.KEY_EIGHT] = ImGuiKey._8,
            [KeyboardKey.KEY_NINE] = ImGuiKey._9,
            [KeyboardKey.KEY_SEMICOLON] = ImGuiKey.Semicolon,
            [KeyboardKey.KEY_EQUAL] = ImGuiKey.Equal,
            [KeyboardKey.KEY_A] = ImGuiKey.A,
            [KeyboardKey.KEY_B] = ImGuiKey.B,
            [KeyboardKey.KEY_C] = ImGuiKey.C,
            [KeyboardKey.KEY_D] = ImGuiKey.D,
            [KeyboardKey.KEY_E] = ImGuiKey.E,
            [KeyboardKey.KEY_F] = ImGuiKey.F,
            [KeyboardKey.KEY_G] = ImGuiKey.G,
            [KeyboardKey.KEY_H] = ImGuiKey.H,
            [KeyboardKey.KEY_I] = ImGuiKey.I,
            [KeyboardKey.KEY_J] = ImGuiKey.J,
            [KeyboardKey.KEY_K] = ImGuiKey.K,
            [KeyboardKey.KEY_L] = ImGuiKey.L,
            [KeyboardKey.KEY_M] = ImGuiKey.M,
            [KeyboardKey.KEY_N] = ImGuiKey.N,
            [KeyboardKey.KEY_O] = ImGuiKey.O,
            [KeyboardKey.KEY_P] = ImGuiKey.P,
            [KeyboardKey.KEY_Q] = ImGuiKey.Q,
            [KeyboardKey.KEY_R] = ImGuiKey.R,
            [KeyboardKey.KEY_S] = ImGuiKey.S,
            [KeyboardKey.KEY_T] = ImGuiKey.T,
            [KeyboardKey.KEY_U] = ImGuiKey.U,
            [KeyboardKey.KEY_V] = ImGuiKey.V,
            [KeyboardKey.KEY_W] = ImGuiKey.W,
            [KeyboardKey.KEY_X] = ImGuiKey.X,
            [KeyboardKey.KEY_Y] = ImGuiKey.Y,
            [KeyboardKey.KEY_Z] = ImGuiKey.Z,
            [KeyboardKey.KEY_SPACE] = ImGuiKey.Space,
            [KeyboardKey.KEY_ESCAPE] = ImGuiKey.Escape,
            [KeyboardKey.KEY_ENTER] = ImGuiKey.Enter,
            [KeyboardKey.KEY_TAB] = ImGuiKey.Tab,
            [KeyboardKey.KEY_BACKSPACE] = ImGuiKey.Backspace,
            [KeyboardKey.KEY_INSERT] = ImGuiKey.Insert,
            [KeyboardKey.KEY_DELETE] = ImGuiKey.Delete,
            [KeyboardKey.KEY_RIGHT] = ImGuiKey.RightArrow,
            [KeyboardKey.KEY_LEFT] = ImGuiKey.LeftArrow,
            [KeyboardKey.KEY_DOWN] = ImGuiKey.DownArrow,
            [KeyboardKey.KEY_UP] = ImGuiKey.UpArrow,
            [KeyboardKey.KEY_PAGE_UP] = ImGuiKey.PageUp,
            [KeyboardKey.KEY_PAGE_DOWN] = ImGuiKey.PageDown,
            [KeyboardKey.KEY_HOME] = ImGuiKey.Home,
            [KeyboardKey.KEY_END] = ImGuiKey.End,
            [KeyboardKey.KEY_CAPS_LOCK] = ImGuiKey.CapsLock,
            [KeyboardKey.KEY_SCROLL_LOCK] = ImGuiKey.ScrollLock,
            [KeyboardKey.KEY_NUM_LOCK] = ImGuiKey.NumLock,
            [KeyboardKey.KEY_PRINT_SCREEN] = ImGuiKey.PrintScreen,
            [KeyboardKey.KEY_PAUSE] = ImGuiKey.Pause,
            [KeyboardKey.KEY_F1] = ImGuiKey.F1,
            [KeyboardKey.KEY_F2] = ImGuiKey.F2,
            [KeyboardKey.KEY_F3] = ImGuiKey.F3,
            [KeyboardKey.KEY_F4] = ImGuiKey.F4,
            [KeyboardKey.KEY_F5] = ImGuiKey.F5,
            [KeyboardKey.KEY_F6] = ImGuiKey.F6,
            [KeyboardKey.KEY_F7] = ImGuiKey.F7,
            [KeyboardKey.KEY_F8] = ImGuiKey.F8,
            [KeyboardKey.KEY_F9] = ImGuiKey.F9,
            [KeyboardKey.KEY_F10] = ImGuiKey.F10,
            [KeyboardKey.KEY_F11] = ImGuiKey.F11,
            [KeyboardKey.KEY_F12] = ImGuiKey.F12,
            [KeyboardKey.KEY_LEFT_SHIFT] = ImGuiKey.LeftShift,
            [KeyboardKey.KEY_LEFT_CONTROL] = ImGuiKey.LeftCtrl,
            [KeyboardKey.KEY_LEFT_ALT] = ImGuiKey.LeftAlt,
            [KeyboardKey.KEY_LEFT_SUPER] = ImGuiKey.LeftSuper,
            [KeyboardKey.KEY_RIGHT_SHIFT] = ImGuiKey.RightShift,
            [KeyboardKey.KEY_RIGHT_CONTROL] = ImGuiKey.RightCtrl,
            [KeyboardKey.KEY_RIGHT_ALT] = ImGuiKey.RightAlt,
            [KeyboardKey.KEY_RIGHT_SUPER] = ImGuiKey.RightSuper,
            [KeyboardKey.KEY_KB_MENU] = ImGuiKey.Menu,
            [KeyboardKey.KEY_LEFT_BRACKET] = ImGuiKey.LeftBracket,
            [KeyboardKey.KEY_BACKSLASH] = ImGuiKey.Backslash,
            [KeyboardKey.KEY_RIGHT_BRACKET] = ImGuiKey.RightBracket,
            [KeyboardKey.KEY_GRAVE] = ImGuiKey.GraveAccent,
            [KeyboardKey.KEY_KP_0] = ImGuiKey.Keypad0,
            [KeyboardKey.KEY_KP_1] = ImGuiKey.Keypad1,
            [KeyboardKey.KEY_KP_2] = ImGuiKey.Keypad2,
            [KeyboardKey.KEY_KP_3] = ImGuiKey.Keypad3,
            [KeyboardKey.KEY_KP_4] = ImGuiKey.Keypad4,
            [KeyboardKey.KEY_KP_5] = ImGuiKey.Keypad5,
            [KeyboardKey.KEY_KP_6] = ImGuiKey.Keypad6,
            [KeyboardKey.KEY_KP_7] = ImGuiKey.Keypad7,
            [KeyboardKey.KEY_KP_8] = ImGuiKey.Keypad8,
            [KeyboardKey.KEY_KP_9] = ImGuiKey.Keypad9,
            [KeyboardKey.KEY_KP_DECIMAL] = ImGuiKey.KeypadDecimal,
            [KeyboardKey.KEY_KP_DIVIDE] = ImGuiKey.KeypadDivide,
            [KeyboardKey.KEY_KP_MULTIPLY] = ImGuiKey.KeypadMultiply,
            [KeyboardKey.KEY_KP_SUBTRACT] = ImGuiKey.KeypadSubtract,
            [KeyboardKey.KEY_KP_ADD] = ImGuiKey.KeypadAdd,
            [KeyboardKey.KEY_KP_ENTER] = ImGuiKey.KeypadEnter,
            [KeyboardKey.KEY_KP_EQUAL] = ImGuiKey.KeypadEqual
        };
}